### ISSUE TITLE
workaround  for messaging menu indicator broken?

### ISSUE THREAD

**Issue by tristan-k** [cheshire-mouse/hexchat-indicator#3]
I'm using `Ubuntu 15.04 64bit` with `HexChat 2.10.2` and installed the `xchat-indicator 0.3.11-0ubuntu7` package. I followed the workaround for the bug which starts a new instance  when clicking on the messaging menu indicator, but it still wont resume the state of hexchat. Just to be clear: I want to close the app window so its gone from the task switcher and bring it back with the indicator.

Can someone confirm this behaviour or provide a solution?

**Comment by cheshire-mouse** [comment]
xchat-indicator will now work with hexchat. You need to install hexchat indicator from this repo (see readme) and use workaround (readme once again). 
P.S. It would be better to uninstall xchat and xchat-indicator if you will use hexchat

**Comment by tristan-k** [comment]
I already uninstalled the package and installed form github repo source again, but the issue remains.

**Comment by cheshire-mouse** [comment]
Checked this out once again (ubuntu 15.04 x64 installed from scratch in the virtualbox)
And workaround still works :)
Here is a step-by-step command list, may be you have missed something. And I'd uninstall hexchat first and remove it's config folder $HOME/.config/hexchat (or at least move it to another location).
- sudo apt-get install hexchat
- sudo apt-get install git
- sudo apt-get install libindicate-dev libunity-dev libmessaging-menu-dev automake
- git clone https://github.com/cheshire-mouse/hexchat-indicator.git
- cd hexchat-indicator/
- ./configure
- make
- cp ./.libs/indicator.so $HOME/.config/hexchat/addons
- sudo mkdir /usr/local/share/applications
- sudo cp /usr/share/applications/hexchat.desktop /usr/local/share/applications/hexchat.desktop
- sudo nano /usr/local/share/applications/hexchat.desktop
- Now you'll have to find "Exec=hexchat %U" in the [Desktop Entry] section (there are two sections and two Exec lines, so be careful),
  comment it and add a new one, it will look like this:

```
#Exec=hexchat %U
Exec=sh -c "flock -n -x /var/run/lock/hexchat.lock -c hexchat || hexchat --existing -c 'gui show'"
```
- restart your PC

**Comment by tristan-k** [comment]
Thanks for your efforts. Im using hexcat from `sudo add-apt-repository -y ppa:gwendal-lebihan-dev/hexchat-stable`. Can you check that out too. Maybe its related.

**Comment by cheshire-mouse** [comment]
Read your problem again, and I think, I understand what you want.
Closing hexchat window will close the program, it would be impossible to resume it through messaging menu. I use this trick: create new keyboard shortcut in the hexchat: 
Key: Ctrl+H (or something you like)
Action: Run Command
Data1: /GUI HIDE

And now Ctrl+H will hide the window and messaging menu will resume it

**Comment by cheshire-mouse** [comment]
Hexchat from ppa repo works the same way as the one from ubuntu repo
